using System;
using Ticketing.Domain.Entities;
using Ticketing.Domain.Enums; // For TicketTypeEnum and TicketStatus

namespace Ticketing.Application.DTOs
{
    public class TicketDto
    {
        public Guid TicketID { get; set; }

        /// <summary>
        /// Type of the ticket (Standard, VIP, Student, etc.)
        /// </summary>
        public TicketTypeEnum Type { get; set; }

        /// <summary>
        /// Price of the ticket
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Optional discount code applied to the ticket
        /// </summary>
        public string? DiscountCode { get; set; }  // Nullable – not required

        /// <summary>
        /// Current status of the ticket
        /// </summary>
        public TicketStatus Status { get; set; }

        /// <summary>
        /// ID of the reservation this ticket belongs to
        /// </summary>
        public Guid ReservationID { get; set; }

        /// <summary>
        /// QR Code as base64 data URL (generated by system, not provided by user)
        /// </summary>
        public string? QRCode { get; set; }  // Nullable – generated on demand

        public DateTime CreatedAt { get; set; }

        public DateTime UpdatedAt { get; set; }
    }
}